### PR TITLE
Use GridLayout for most of ConfilictWindow.

### LINKED ISSUE #107: Beautfy the Conflict window
Instead of a GroupLayout, the Conflict window should use a GridLayout which allows to neatly arrange stuff in columns and rows. Here's a mockup: Imockup

- I'd keep it all left-aligned with the first row spanning two columns.
- As we eventually would like to make the source and destination objects clickable, I think it's more consistent to not only use the parent paths, but the path+objects even if the file name is also mentioned explicitely in the 2nd row.
- The dates and size rows could be italicized and/or tinted slightly lighter that the source/destination path row.

Eventually, it'd be nice if the Conflict window would sport a darker vertical strip to the left and a "!" icon, like BAlerts do. (e.g. in Terminal: `alert --warning "File already exists in target folder."`

### PR DESCRIPTION
**Pull request by owenca**
Also, change mouse cursor to FOLLOW_LINK for source/target folder path.

Fixes #107

### CODE REVIEW

**Comment by owenca** [comment]
conflict window

**Comment by owenca** [comment]
What's Tracker's signature? I suppose that the way to launch it is through `be_roster->Launch`.

**Comment by owenca** [comment]
Tracker source code uses `kTrackerSignature`. Which header is it defined in?

**Comment by humdingerb** [comment]
Since "kTrackerSignature" is defined in a [private header](http://xref.plausible.coop/source/search?q=kTrackerSignature&defs=&refs=&path=headers&hist=&type=&project=haiku) you can just as well use the signature directly: "application/x-vnd.Be-TRAK".
The "Select" message is 'Tsel', if you haven't found that already.

**Comment by humdingerb** [comment]
Should I merge now, or let you add the opening the Tracker window and selecting the file to this PR?

**Comment by humdingerb** [comment]
Since I'm unable to comment in-line with Web+ at the moment...

What do you think about grouping the information by introducing some padding. Like this:
```
.AddGrid(B_USE_HALF_ITEM_SPACING, 0)
	.Add(_CreateLabelView(B_TRANSLATE("File name")), 0, 0)
	.Add(new BStringView("", file), 1, 0)
	.Add(BSpaceLayoutItem::CreateVerticalStrut(B_USE_HALF_ITEM_SPACING), 0, 1)
	.Add(_CreateLabelView(B_TRANSLATE("Source folder")), 0, 2)
	.Add(new FolderView(src), 1, 2)
	.Add(_CreateAttrView(file, src), 1, 3)
	.Add(BSpaceLayoutItem::CreateVerticalStrut(B_USE_HALF_ITEM_SPACING), 0, 4)
	.Add(_CreateLabelView(B_TRANSLATE("Target folder")), 0, 5)
	.Add(new FolderView(dest), 1, 5)
	.Add(_CreateAttrView(file, dest), 1, 6)
	.Add(BSpaceLayoutItem::CreateVerticalStrut(B_USE_HALF_ITEM_SPACING), 0, 7)
	.Add(_CreateLabelView(B_TRANSLATE("Rule name")), 0, 8)
	.Add(new BStringView("", desc), 1, 8)
	.End()
```

Also, since file name may contain spaces, I suggest putting file name, paths, and rule name in inverted commas.

**Comment by owenca** [comment]
Thank you very much! Can you merge this PR first? I will work on making the source/target folders clickable next.

**Comment by owenca** [comment]
I found the same signature from the Be Book, but it didn't bring up the Tracker window. When I used Filer signature, my code worked, so I thought Tracker signature changed in Haiku. I will try it again.

**Comment by humdingerb** [comment]
Merged. Maybe a look at what Quicklaunch does gives a clue what's wrong:
https://github.com/humdingerb/quicklaunch/blob/master/MainWindow.cpp#191

As you suggested before, when launching the tracker window, it may be better to wait on a reply, before sending the "Select" message. That's avoid the window still being populated when receiving the select message.

**Comment by owenca** [comment]
Thanks! I will try your space padding code. I thought about using `.AddStrut()` but felt it looked ok without extra spacing.

I didn't think the quotes for the file name and folder paths were necessary because they are in a field by themselves, not within a sentence like before. Do you still think we should add the quotation marks? Anyway, I don't think it should be done for the rule name.

**Comment by humdingerb** [comment]
Maybe you're right about the quotes... Let's leave 'em out for now and see how it looks with/without.

Have a look at the "Get info" of Tracker. Filer could emulate its style, i.e. using a lighter colour for the info (black for the labels), same blue for the paths, same date-format.

**Pull request merged**
