### PR TITLE
Fixes issue #63:

### PR DESCRIPTION
**Pull request by owenca**
Adds support for file size units (bytes, KiB, MiB, GiB, and TiB).

Also, looks for . and .. when deciding if the user has
given a folder path to the "Add to archive" action.

### CODE REVIEW

**Comment by owenca** [comment]
1of2
2of2

**Comment by humdingerb** [comment]
I did a clean build, but Filer refuses to launch. Started from Terminal, I see "Abort Abort".

**Comment by humdingerb** [comment]
Looks like something changed in the settings. After deleting those, Filer starts. But that shouldn't be the case, right? Old Filer settings should be readable and silently converted.

**Comment by owenca** [comment]
I have always done the following two tests when making changes to the rules format:

1. Run "rm -r ~/config/settings/Filer".
Run Filer v1.1.0 and let it create the default rules.
Run "cp ~/config/settings/Filer/FilerRules ~".
Then run the new Filer.

2. Run "rm -r ~/config/settings/Filer".
Run the new Filer without creating the default rules.
Run "cp ~/FilerRules ~/config/settings/Filer".
Run the new Filer again.

**Comment by owenca** [comment]
You will have a problem if you don't restart from scratch or from the v1.1.0 format because the backward compatibility is only between the latest format and the v1.1.0 format, not between the intermediate formats post-v.1.1.0, as we have discussed before.

**Comment by humdingerb** [comment]
> only between the latest format and the v1.1.0 format, not between the intermediate formats

Oh, right. Sorry, I forgot about that...

To be honest, I didn't have too close a look at these changes, and find it increasingly difficult to judge what's done whre in Filer... :)

So, I'll just pose the questions, in the hope I didn't misunderstood too much...

Wouldn't it be easier to always save the size in a rule as bytes and only devide/multiply by 1024 when reading/filling the size text control depending on the unit popup menu?

How do you deal localized input in the "size" text control. E.g. Germans use a "," where English use ".". Not totally sure, but POSIX functions like https://linux.die.net/man/3/strtof should be locale aware under Haiku.
For the other way around, filling the size text control when loading the rule, there should be something at http://cgit.haiku-os.org/haiku/tree/headers/os/locale

**Comment by humdingerb** [comment]
If you want, I can merge this PR and can refine the code (if necessary) in a new PR. We should try to keep code changes small.

**Comment by humdingerb** [comment]
> Wouldn't it be easier to always save the size in a rule as bytes and only devide/multiply by 1024 when reading/filling the size text control depending on the unit popup menu?

Sorry to spam with comments. I now get why you save the unit with the rule. Obviously, you have know the unit to be able to set the unit pop-up when displaying the rule... Sorry about that.

**Comment by owenca** [comment]
Sorry I didn't see your comments before updated the commit, twice.

Another reason for saving the unit type into the FilerRules file is to keep the user's preference: if he saves 1024 KiB, we don't want him to see 1 MiB when his rules are reloaded.

After adding the "bytes" unit and thinking of the need to support drag&drop for file size, I have decided to only support whole numbers for TEST_SIZE. (If a file is drag&dropped, the unit will reset to "bytes".) If the user wants to specify "1.5 MiB", he can instead use "1536 KiB". This will avoid headaches like rounding or invalidating "100.3 bytes" and localizing the decimal point as you have pointed out.

Because of the rewriting of a significant portion of TestView, more testing of this commit is warranted. If you don't find any bugs after using it for a while, it can be safely merged. :)

**Comment by owenca** [comment]
I have updated the commit a few more times but will stop now so that you can review the PR and test it.

**Comment by humdingerb** [comment]
Seems to work very well. Two things though, you may want to consider for your next PRs:

- For the size-test, do DisallowHar() for non-digits. Floating numbers make no sense for the Bytes unit, but may be useful for KiB, GiB and TiB You may want to consider allowing it for those.

- "is" and "is not" is only useful when using the Bytes unit. KiB, GiB and TiB get rounded all the time, e.g. 3.5 KiB is 3584 bytes, but the user will see some file shown as 3.5 KiB, too, when it is 3583 or 3582 bytes. A rule "When size is 3.5 KiB" wouldn't be triggered in that case.
If you can suppress "is/isnot" for all but the Bytes unit, that would be nice.

**Comment by owenca** [comment]
> For the size-test, do DisallowHar() for non-digits.

Done. Please see PR #70.

**Comment by owenca** [comment]
> "is" and "is not" is only useful when using the Bytes unit.

Indeed. Also, "is at least/most" is kind of redundant to "is more/less than" for file size comparisons, especially if we allow fractional numbers.

**Pull request merged**
