### PR TITLE
Add extra messaging between Filer and Tracker to ensure the file in

### PR DESCRIPTION
**Pull request by owenca**
conflict is selected in Tracker for source/target folder.

### CODE REVIEW

**Comment by owenca** [comment]
@humdingerb: can you see if this works with your 400-file folder? If it works, you may want to add a delay in the do-while loop so that Filer doesn't try to flood Tracker's message queue.

**Comment by humdingerb** [comment]
Doesn't work unfortunately. The ConflictWindow becomes unresponsive and the target folder's Tracker window, though having selected the file, keeps popping to the front. Looks like it's still being hammered with messages. Closing the Tracker window leaves the ConflictWindow still unresponsive.

**Comment by humdingerb** [comment]
I  poked a bit more with Debugger.
In `cnt.AddSpecifier("Window", fFolderRef.name);` fFolderRef.name contains of course the folder name, e.g. for /boot/home/downloads it's "downloads". This onl works, if in the Tracker prefs the setting "Show folder location in title tab" is deactivated. I have it activated, so the title actually shows "/boot/home/downloads". Which then isn't found.

I expect it's easiest to look for both window titles?

**Comment by humdingerb** [comment]
I now changed your code to this, which seems to work. Tell me if it's horrible or OK... :)

```
void
FolderPathView::_OpenFolder()
{
	be_roster->Launch(&fFolderRef);

	BMessage cnt(B_COUNT_PROPERTIES);
	cnt.AddSpecifier("Selection");
	cnt.AddSpecifier("Poses");
	cnt.AddSpecifier("Window", fFolderRef.name);

	BPath path(&fFolderRef);
	BMessage cnt2(B_COUNT_PROPERTIES);
	cnt2.AddSpecifier("Selection");
	cnt2.AddSpecifier("Poses");
	cnt2.AddSpecifier("Window", path.Path());

	int32 count = 0;
	int32 count2 = 0;
	BMessage reply;
	BMessage reply2;
	BMessenger msgr("application/x-vnd.Be-TRAK");
	do {
		snooze(100000);	// wait 0.1 sec
		msgr.SendMessage(&cnt, &reply);
		reply.FindInt32("result", &count);

		msgr.SendMessage(&cnt2, &reply2);
		reply2.FindInt32("result", &count2);
	} while (count != B_NO_ERROR && count2 != B_NO_ERROR);

	BMessage sel('Tsel');
	sel.AddRef("refs", &fFileRef);
	msgr.SendMessage(&sel);
}
```

**Comment by owenca** [comment]
Thanks for finding the cause! The best way is to check if "Show folder location in title tab" checkbox of Tracker prefs is checked, and choose either leaf name or full path accordingly. (Another pitfall is "Hide dotfiles".) We can just use your code as is (or leave this feature out) for now and enhance it in the future.

BTW, I have confirmed that Tracker doesn't send a reply to 'Tsel', so it seems that using the scripting feature of Tracker is the only way.

**Comment by CodeforEvolution** [comment]
I Don’t know if this might help reduce the amount of code or not, though this possibly could be a helpful function:
https://cgit.haiku-os.org/haiku/tree/headers/private/shared/OpenWithTracker.h

**Comment by humdingerb** [comment]
@owena,  I'm afraid, I haven't thought it through enough. If I remove the snooze() in the loop, the selection still fails for largely populated folders. Our do-while loop only waits for the Tracker window to be created, it doesn't guarantee that it is fully populated with all the files in that folder. So our msgr.SendMessage(&sel) to select our file may still be sent too early.

How did investigate how to script Tracker to know when the Tracker window is up? Can the same be done for when the window is completely populated? Otherwise all our song and dance is for naught and we can just blindly snooze fo 1/3 sec as Quicklaunch does it... Which might not be long enough for very large folders or over the network...

At worst, people have to click the link in the ConflictWindow again when the window finally is completely populated...

Any more ideas? :)

**Comment by humdingerb** [comment]
Sorry for being an idiot...
I just realised that the BMessage cnt(B_COUNT_PROPERTIES) stuff actually is counting the selected files, not just checking if the Tracker window is up. How could I have missed that?

Anyway, this now seems to work relativel well:
```
...
	do {
		BMessage sel('Tsel');
		sel.AddRef("refs", &fFileRef);
		msgr.SendMessage(&sel);
	
		snooze(100000);	// wait 0.1 sec

		msgr.SendMessage(&cnt, &reply);
		reply.FindInt32("result", &count);

		msgr.SendMessage(&cnt2, &reply2);
		reply2.FindInt32("result", &count2);
	} while (count == 0 && count2 == 0);

	snooze(200000);	// wait 0.2 sec
	BMessage sel('Tsel');
	sel.AddRef("refs", &fFileRef);
	msgr.SendMessage(&sel);
```

Now the file will definitely be selected. I added the final snooze(200000) and 'Tsel' message, because it may be that the window is still being populated after our file appeared and was selected. This will scroll it back into view.
Of course, for really huge folders additional 0.2 sec may not be enough. But anything longer will lead to responsiveness problems.

**Comment by humdingerb** [comment]
I since found a better way to do all this by copying what Web+'s Downloads window does when you choose "Open containing folder" from the context menu, (see [DownloadProgressView.cpp](http://xref.plausible.coop/source/xref/haiku/src/apps/webpositive/DownloadProgressView.cpp#532):
```
void
FolderPathView::_OpenFolder()
{
	BEntry selected(&fFileRef);
	if (!selected.Exists())
		return;

	// Ask Tracker to open the containing folder and select the
	// file inside it.
	BMessenger trackerMessenger("application/x-vnd.Be-TRAK");

	if (trackerMessenger.IsValid()) {
		BMessage selectionCommand(B_REFS_RECEIVED);
		status_t status = selectionCommand.AddRef("refs", &fFolderRef);

		node_ref selectedRef;
		if (selected.GetNodeRef(&selectedRef) == B_OK) {
			selectionCommand.AddData("nodeRefToSelect", B_RAW_TYPE,
				(void*)&selectedRef, sizeof(node_ref));
		}
		trackerMessenger.SendMessage(&selectionCommand);
	}
}
```
There's just one problem: If you check in Debugger, the line `status_t status = selectionCommand.AddRef("refs", &fFolderRef);` adds a ref that is missing the "name". I'm still trying to figure out what's wrong...

**Comment by owenca** [comment]
Didn't you want to use `&fFileRef` instead? Anyway, wonderful news that you found the right way (instead of my convoluted way) to solve this problem! Thank you very much!

**Comment by owenca** [comment]
@CodeforEvolution, thank you for the info! I will take a look and see if I can make good use of it.

**Comment by humdingerb** [comment]
Yeah, nice that there is a "nodeRefToSelect" that Tracker understands. :)

&fFolderRef should be correct. We send a BMessage with "what" = B_REFS_RECEIVED and AddRef() the folder (fFolderRef) we want Tracker to open. We also AddData() the node_ref of the file (FileRef) in that folder we want to have selected (and scrolled to).

The strange thing is, that even though the selectionCommand message shows an incomplete refs to the folder ("name" is empty) in Debugger, the correct folder is indeed opened, but the file isn't selected. However, if I cast the "nodeRefToSelect" of the message to node_ref,  I see the correct device and node...

Here's the screenshot of Debugger at `selectionCommand.AddRef("refs", &fFolderRef);`:
http://img.ctrlv.in/img/17/08/12/598ed16094782.png

**Comment by humdingerb** [comment]
Turns out it's a limitation of Debugger, as Rene mentioned on the haiku-3rd-party ML.
So, I committed the code, though things are still problematic when the window is still being populated after selecting the file...

**Comment by owenca** [comment]
Please see my comments to https://github.com/HaikuArchives/Filer/commit/0837dd864cca8c7cd65df74a3af1cbaf8c0e5890.

**Pull request merged**
