### PR TITLE
Make ConflictWindow more informative.

### LINKED ISSUE #101: Conflict window: also shows location
Case of example: a lot of rules and folders where to move files (eg pictures or graphic files, but also documents based on the content - eg. in some rules, I trigger shell scripts which check the content or the attributes of text files): in such cases when a conflict window appears, it will only show the file name but not the location (folder) where the conflict occurs. So would be nice - for sake of completeness - if the conflict window would also show the folder where the file is already present (and maybe also the source folder, since most of rules are managed by AutoFiler which automatically works in background.)

### PR DESCRIPTION
**Pull request by owenca**
Fixes #101

### CODE REVIEW

**Comment by owenca** [comment]
Maybe this would be better:

File already exists in target folder.

File name: ...
Source folder: ...
Target folder: ...
Rule name: ...

**Comment by humdingerb** [comment]
Sounds better, yes.
How difficult would it be to show file size and modified date in brackets behind source and target path?
Can a click on the source/target view Launch() the file?
Just say No if you don't have the time or motivation ATM... :)

**Comment by owenca** [comment]
It will take me a while to implement your excellent ideas, but that wouldn't affect the catkeys. Can you merge this one first?

PS: I would put the brackets below the folders to not make the window too wide:
...
Source folder: ...
        [date, size]
Target folder: ...
        [date, size]
...

**Comment by humdingerb** [comment]
Sounds like a plan.

**Pull request merged**
