### PR TITLE
Make source/target folders of ConflictWindow clickable.

### PR DESCRIPTION
**Pull request by owenca**
Add vertical padding within the grid layout in `ConflictWindow`
(thanks to @humdingerb's code).

Also, add long-click popup menus for opening source/target folder/file.

Finally, make `ConflictWindow` resemble the "Get info" window of Tracker:

* Change the format of date/time.

* Change the color of source/target folder path.

* Right-align labels.

* Make the text color of the 2nd column lighter.

* Remove the italic face for date/time and size.

* Change the visual cue for mouse over the source/target folder path.

### CODE REVIEW

**Comment by owenca** [comment]
conflictwindow

**Comment by owenca** [comment]
I think this is it:

conflict window

**Comment by humdingerb** [comment]
What do you think about right-aligning the labels?

Right-aligned

```
BStringView*
ConflictWindow::_CreateLabelView(const char* label)
{
	BString text(label);
	text += ':';

	BStringView* labelView = new BStringView("", text);
	labelView->SetAlignment(B_ALIGN_RIGHT);
	
	return labelView;
}
```

Also, what do you think about doing an "AttrView" similar to "FolderView" that has the text coloured like [Tracker's InfoWindow.cpp](http://xref.plausible.coop/source/xref/haiku/src/kits/tracker/InfoWindow.cpp#1711). It visually distinguishes the labels fromt he attributes subtly.

BTW, if you generally agree, but don't find the time ATM, just say so and I'll try my hand at it... :)

**Comment by owenca** [comment]
Now I see "Get info" of Tracker right-align the labels. I tried to make the file name and attribute values lighter using the code from Tracker, but it didn't work. I will try it again.

**Comment by owenca** [comment]
I still can't make the code from InfoWindow.cpp work. It doesn't change the text color of labels at all. I think I have to subclass `BStringView` and reimplement its `Draw` function with the code.

IMO, the contrast shown in the "Get info" window of Tracker is too subtle to notice the difference. OTOH, using `B_WINDOW_INACTIVE_TEXT_COLOR` here may be too much. (I commented out the code that italicizes data/time and size because it's probably not needed anymore.)

conflictwindow again

Shall we settle with this version or should I try to see if subclassing would work?

**Comment by humdingerb** [comment]
Yep. If done, it has to be by subclassing and setting the colour in Draw(). While I do like GetInfo's subtlety, B_WINDOW_INACTIVE_TEXT_COLOR looks nice enough. Though it may look differnently if people change system colours. Though mixing colours may also suffer from some cases of customization.
I leave it up to you (or a user filing a complaint. :) )

**Comment by owenca** [comment]
One more thing, I think `B_LINK_HOVER_COLOR` is better than changing the cursor. I will push the code if you feel the same way.

I will leave the implementation of the contrast as is for now. (You think removing the italic style is better?)

**Comment by humdingerb** [comment]
sure, go  ahead. let's get rid of the italic, too. cleaner without it.

**Comment by owenca** [comment]
Done. BTW, did you see a problem with opening large folders that fail to select the file? I didn't add a delay because I tried a couple large folders and didn't see the problem. (AFAIK, Tracker doesn't send a reply.)

**Comment by owenca** [comment]
It turns out that there is no need to subclass `BStringView` in order for `mix_color` to work, so I have made the contrast the same as "Get info" of Tracker.

Also, to mimic Tracker, I have added a visual cue for `MouseDown` when the source/target folder path is clicked.

ultimate confilictwindow

**Comment by owenca** [comment]
I will be away from Filer and Haiku coding for a couple of weeks. Good luck with the remaining work (catkeys, Makefile, etc.) before the v1.2.0 release!

**Comment by humdingerb** [comment]
Merged.

> BTW, did you see a problem with opening large folders that fail to select the file? I didn't add a delay because I tried a couple large folders and didn't see the problem. (AFAIK, Tracker doesn't send a reply.)

I do see this issue when the file is in a folder containing 400+ files. Of course, it also depends on the used media. If you're going over network, you may experience seconds of delay. So adding a delay (as I did in Quicklaunch) is really just a lazy cop-out.
I'll look into using a SendMessage() with return message for the selection. I hope Tracker answers with a "false" or something, if the selecting failed and I resend the message a few times until is succeeds. That's the plan at least... :)

I have added a StripView as it's found in SoftwareUpdater. It makes the window look even more like GetInto, and also BAlerts:

[!Image of new Conflict[(http://img.ctrlv.in/img/17/08/10/598c39663d8e6.png)

Also added some space above/below the file/path info.
And re-added your mouse pointer changes. It's more obvious that just a colour change. GetInfo should do that too, as AboutSystem already does.

Seen your context menu to "Open file/folder". I had the same idea! :)
Now I just have to find out why there is such a long delay until it appears, and doesn't at all when only quickly right-clicking it...

Anyway, thanks a lot for your work! I'm sure I couldn't have done it, let alone this fast.
Hope to see you again soon!

**Comment by humdingerb** [comment]
Preview doesn't work ATM wth Web+... :(
The window: [!Image of new Conflict](http://img.ctrlv.in/img/17/08/10/598c39663d8e6.png)

**Pull request merged**
