### PR TITLE
Check the MIME type when drag&dropping a file to Test/Action text controls

### PR DESCRIPTION
**Pull request by owenca**

### CODE REVIEW

**Comment by owenca** [comment]
This should be it.

**Comment by humdingerb** [comment]
This really seemed to have fixed it, thanks!
So that update_mime_info() tries to set a MIME type for a file, even when it sits on a filesystem that doesn't report a MIME type itself?

Also, you comment out SetupTypeMenu(), because it's never called by anyone, right?
I wonder exactly what its purpose was supposed to be. After all, the "Type" menu does contain the atrributes of super-types, e.g. "Audio file", "Image file", "Video file"...

**Comment by owenca** [comment]
> So that update_mime_info() tries to set a MIME type for a file, even when it sits on a filesystem that doesn't report a MIME type itself?

Yes, but it may still fail, for example, with files on ext2/ext3 partitions, which don't even show up in macOS.

It seems Tracker and BFilePanel have more code that better sniffs out the MIME type, but I don't see an easy way to extract that functionality.

> Also, you comment out SetupTypeMenu(), because it's never called by anyone, right?

Yes. I ran into it by accident and suspected that it was obsolete for the same reason you mentioned.

**Comment by humdingerb** [comment]
> It seems Tracker and BFilePanel have more code that better sniffs out the MIME type, but I don't see an easy way to extract that functionality.

It's OK. It's working very well now, even if it has to accept all unknown filetypes that are dropped/selected in the file panel.

**Comment by owenca** [comment]
I wasn't very happy because the code was convoluted and it didn't always sniff out the MIME type. Then I poked around and found a better and simpler way: [PR #120](https://github.com/HaikuArchives/Filer/pull/120)

**Pull request merged**
