### PR TITLE
Store rules in flattened message instead of SQLite

### PR DESCRIPTION
**Pull request by JadedCtrl**
Swaps over from using SQLite for rule storage to a flattened message, migrating over old SQL rules and backing up the old DB.

### CODE REVIEW

**Comment by humdingerb** [comment]
Did a few tests and it works fine, thanks!

So SQLite is now only used to migrate older FilterRules over to flatB, right? I wonder how long we should support that migration and therefore the SQL dependency.

**Comment by JadedCtrl** [comment]
Maybe a year or two after the next version bump on HaikuPorts?

**Comment by humdingerb** [comment]
Sounds good. I create #129 as a reminder.

**Comment by humdingerb** [comment]
Given that, I think we should release a new minor version as soon as convenient. Do you have any work that you'd like to be included that you can finish in the next few weeks?

**Comment by JadedCtrl** [comment]
I'd like to get in a couple patches, yea, shouldn't be more than a week or two.

**Comment by humdingerb** [comment]
Very good, no hurry.

**Pull request merged**
