### PR TITLE
fix issue #15

### PR DESCRIPTION
**Pull request by owenca**
refactor MoveAction and CopyAction, prevent silently overwriting existing files by Copy/Move actions, and ask user to choose between Overwrite and Skip with an option to have remaining files processed the same way

### CODE REVIEW

**Comment by owenca** [comment]
The Conflict window can be made prettier and more informative. I will improve it in the near future.

**Comment by owenca** [comment]
I have added comments to the semaphore code.

**Comment by owenca** [comment]
Now AutoFiler will only cause one dialog to pop up at a time.

**Comment by humdingerb** [comment]
I'd love to try it. When will you push this change to your fork? :)

**Comment by owenca** [comment]
I had done it before adding the above comment, but I will push another one that should also remember the ask/overwrite choices for any directory in AutoFiler. It's about 80% done.

**Comment by owenca** [comment]
Everything seems to work in both Filer and AutoFiler.

**Comment by humdingerb** [comment]
From a quick test, it all works well when dropping files onto the (replicated or in-app) dropzone and when using "Open with..." on selected files. Nice!

There's one issue with AutoFiler though: If you activate the "Do this for all files" checkbox, AutoFiler will remember this setting also for all subsequent file-drops. Only after restarting AutoFiler, this setting is forgotten. The checkmark should only apply to the current file-drop.

**Comment by owenca** [comment]
I had noticed it, too but believed there was not much that could be done without fundamentally changing AutoFiler, which currently monitors node changes in the background and doesn't know much more about these changes, like which ones were initiated by the user through drag & drop, or which ones were triggered by a program with auto safe. I can't come up with a clean solution that will accurately group the node changes.

**Comment by pulkomandy** [comment]
Looks good to me. The comment about the semaphore are a bit verbose ("create semaphore with a count of 0" was rather obvious for example) but that's ok.

I would do a single comment at the declaration of fSemId, something like this:
/* This semaphore is used to block another thread on the choice window. When the other thread calls Go(), it blocks on the semaphore. When the window is closed, the semaphore is deleted, and this releases the calling thread which can then continue its execution.
*/

Also, am I right that Filer more or less implements https://www.haiku-os.org/glass_elevator/rfc/sorting_chute/ ? Maybe we should add a link in that page and mark it as "complete" then?

**Comment by humdingerb** [comment]
@pulkomandy : I didn't even know of that RFC page, or the "Glasselevator" pages in general... :)
How is it marked as "complete"? Just add an info box at the top?

**Comment by humdingerb** [comment]
@owenca 
>  I just can't come up with a clean solution that will accurately group the node changes.

Maybe it's enough to:
* Save the time when you invoke Filer from AutoFiler
* Next time you invoke Filer from AutoFiler, compare times and if more than 5 seconds have passed, remove the "Do for all files" option.
That way, at least the files added in a 5 second window are grouped with the "Do for all files" option.

Ideally, the rules would have a "Conflict" setting added where you can define the default action (Skip/Rename/Ask user).

**Comment by owenca** [comment]
@pulkomandy Thanks! I added a comment block in ConflictWindow.h and condensed the comments in ConflictWindow.cpp as you suggested.

**Comment by owenca** [comment]
@humdingerb Thanks for the good idea! It worked pretty well but not always.

For example, AutoFiler is monitoring the Home folder, and there is a Move rule that moves PDF files from Home to Documents. Now x.pdf and y.pdf are being dropped or pasted in Home where x.pdf doesn't exist but y.pdf does, so x.pdf is dropped in Home but y.pdf is paused by a dialog from Tracker.

If x.pdf already exists in Documents, AutoFiler will wait for the user to act on Filer's dialog. If the user checks the "Do this for all files" box and then clicks on either Skip or Replace, AutoFiler processes x.pdf and then continues to process other files (from Home and other monitored folders) in its queue. Now the user clicks on Replace in Tracker's dialog, so y.pdf is dropped in Home.

If the elapsed time exceeds 5 seconds or whatever time period, the AutoFiler settings will be reset, and Filer will pop up its dialog for B. Even if the period is set to 10 seconds or longer, the user can still out-wait it.

So I set the period to 1 second for now, which should be more than enough to filter out consecutive Filer launches (with "Do this for all files" set to true) by AutoFiler.

**Comment by humdingerb** [comment]
Good to hear it's working adequately well!

On 16 March 2017 at 02:47, Owen <notifications@github.com> wrote:

> Now x.pdf and y.pdf are being dropped or pasted in Home where x.pdf
> doesn't exist but y.pdf does, so x.pdf is dropped in Home but y.pdf is
> paused by a dialog from Tracker.


Yeah, that'll always be an issue. Not a big problem I'd say, cases where
you keep files that fit a rule in a monitored folder should be very few.
Normally, I imagine that you file away those specific files of a folder and
set the AutoFiler to monitor it from then on. So, maybe a slight hickup the
first time around, but then it should work.

Nicely done!

Regards,
Humdinger

--
Did you know:
  If half the Haiku supporters at http://www.goodsearch.com
  made 10 searches a day, we could have a fulltime developer.

**Comment by owenca** [comment]
Everything works really well except for a minor problem that surfaces at random: when the user selects "Do this for all files" for a group of dropped files while AutoFiler is running, sometimes the choice doesn't get passed to subsequent files in the group, so the user will be prompted again. This problem exists with or without the timer in AutoFiler.

I can think of three possible causes:
1. AutoFiler launches Filer for one file in the group, but before it sends a synchronous message to Filer and receives a reply, another thread launches Filer for another file in the group.
2. AutoFiler didn't get a reply from Filer for some reason, e.g., Filer has finished and quit before receiving the request.
3. Filer did get the request from AutoFiler but quit immediately on B_QUIT_REQUESTED without first processing the request in its message queue.

I have eliminated #1 above by using a BLocker, and #2 can't occur if Filer has prompted the user. That leaves only #3, which is possible only if B_QUIT_REQUESTED is not appended to the message queue but processed immediately. Am I correct?

**Comment by owenca** [comment]
It was none of the above, but I narrowed it down to this: sometimes AutoFiler gets a B_BAD_PORT_ID error after Filer has successfully sent AutoFiler a reply because "the reply port was deleted while waiting for a reply" according to [BeBook](https://www.haiku-os.org/legacy-docs/bebook/BMessenger.html#BMessenger_MemberFunctions).

**Comment by owenca** [comment]
I just pushed another squashed commit with some cleanups and minor tweaks. It's ready to be merged, I think.

**Comment by humdingerb** [comment]
It does seem to work very well! Maybe add your comment above, "sometimes AutoFiler gets a B_BAD_PORT_ID error after Filer has successfully sent AutoFiler a reply because "the reply port was deleted while waiting for a reply" according to BeBook." to the commit message and add an issue for that.
If others don't find anything else, I'm for merging.

While the looks of the conflict window aren't perfect yet, Filer is now much more usable with your changes. Thanks a lot!

**Comment by owenca** [comment]
You are welcome!

I have added the comment to the commit message and will create an issue later. The conflict window is far from perfect. I was struggling with the layout builder and only made the window functional. We can have a makeover when adding Rename next.

I am really curious about the B_BAD_PORT_ID error. Can someone help me track it down?

**Comment by humdingerb** [comment]
Thanks a lot!

**Pull request merged**
